In [2]:
# ============================================================
# Lesson 1: Data Loading & Understanding
# Project: Placement Analytics & Prediction System
# ============================================================

import pandas as pd
import numpy as np
import os

print("✅ Libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

✅ Libraries imported successfully!
Pandas version: 3.0.4
NumPy version: 2.5.0

In [4]:
# Configure Display Options 
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

# Load the Dataset 
DATA_PATH = '../data/raw/placement_data.csv'

df = pd.read_csv(DATA_PATH)

print("✅ Dataset loaded successfully!")
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

✅ Dataset loaded successfully!
Rows    : 215
Columns : 15

In [5]:
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.00,Mkt&HR,58.80,Placed,270000.00
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.00
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.00
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.00

In [6]:
df.sample(5, random_state=42)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
200,201,M,69.00,Others,60.00,Others,Commerce,65.00,Comm&Mgmt,No,87.55,Mkt&Fin,52.81,Placed,300000.00
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.00
138,139,F,82.00,Others,64.00,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.00
176,177,F,59.00,Central,60.00,Others,Commerce,56.00,Comm&Mgmt,No,55.00,Mkt&HR,57.90,Placed,220000.00
15,16,F,65.00,Central,75.00,Central,Commerce,69.00,Comm&Mgmt,Yes,72.00,Mkt&Fin,64.66,Placed,200000.00

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 35.0 KB

In [8]:
df.describe()

       sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
count 215.00 215.00 215.00    215.00   215.00 215.00    148.00
mean  108.00  67.30  66.33     66.37    72.10  62.28 288655.41
std    62.21  10.83  10.90      7.36    13.28   5.83  93457.45
min     1.00  40.89  37.00     50.00    50.00  51.21 200000.00
25%    54.50  60.60  60.90     61.00    60.00  57.95 240000.00
50%   108.00  67.00  65.00     66.00    71.00  62.00 265000.00
75%   161.50  75.70  73.00     72.00    83.50  66.25 300000.00
max   215.00  89.40  97.70     91.00    98.00  77.89 940000.00

In [9]:
df['status'].value_counts()

status
Placed        148
Not Placed     67
Name: count, dtype: int64

In [10]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [11]:
for col in df.columns:
    unique_vals = df[col].nunique()
    if unique_vals <= 10:
        print(f"{col} ({unique_vals} unique): {df[col].unique()}")
    else :
        print(f"{col}: {unique_vals} unique values")

sl_no: 215 unique values
gender (2 unique): <ArrowStringArray>
['M', 'F']
Length: 2, dtype: str
ssc_p: 103 unique values
ssc_b (2 unique): <ArrowStringArray>
['Others', 'Central']
Length: 2, dtype: str
hsc_p: 97 unique values
hsc_b (2 unique): <ArrowStringArray>
['Others', 'Central']
Length: 2, dtype: str
hsc_s (3 unique): <ArrowStringArray>
['Commerce', 'Science', 'Arts']
Length: 3, dtype: str
degree_p: 89 unique values
degree_t (3 unique): <ArrowStringArray>
['Sci&Tech', 'Comm&Mgmt', 'Others']
Length: 3, dtype: str
workex (2 unique): <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
etest_p: 100 unique values
specialisation (2 unique): <ArrowStringArray>
['Mkt&HR', 'Mkt&Fin']
Length: 2, dtype: str
mba_p: 205 unique values
status (2 unique): <ArrowStringArray>
['Placed', 'Not Placed']
Length: 2, dtype: str
salary: 45 unique values